const D=[
{id:'math',s:'الرياضيات',t:'التحويلات الهندسية للاقتران التربيعي',i:'📐',d:'الإزاحة الرأسية والأفقية للقطع المكافئ.',intro:'الاقتران الأساسي f(x)=x². في هذا الدرس نتعلم تحريك المنحنى دون تغيير شكله.',o:['استنتاج أثر الإزاحة الرأسية.','استنتاج أثر الإزاحة الأفقية.','تحديد رأس القطع المكافئ.'],e:[['الانسحاب الرأسي','g(x)=x²+k: الموجب للأعلى والسالب للأسفل.'],['الانسحاب الأفقي','g(x)=(x-h)²: h الموجب لليمين، والسالب لليسار.']],sum:'في g(x)=(x-h)²+k يكون الرأس (h,k).',q:[['g(x)=x²+5 يمثل:', ['للأعلى 5','للأسفل 5','لليمين 5','لليسار 5'],0],['(x-3)² يمثل انسحابًا:', ['لليسار 3','لليمين 3','للأعلى 3','للأسفل 3'],1],['رأس (x+2)²-4:', ['(2,4)','(-2,-4)','(-2,4)','(2,-4)'],1],['الانسحاب في (x-1)²+1:', ['يمين 1 وأعلى 1','يسار 1 وأعلى 1','يمين 1 وأسفل 1','يسار 1 وأسفل 1'],0]]},
{id:'arabic',s:'اللغة العربية',t:'الأسماء الممدودة والمقصورة والمنقوصة',i:'📖',d:'تمييز أنواع الأسماء المعتلة الآخر.',intro:'تختلف الأسماء بحسب الحرف الأخير: ألف أو ياء أو همزة قبلها ألف.',o:['التعرف إلى المقصور والمنقوص والممدود.','التمييز بينها في النصوص.','معرفة الإعراب الأساسي.'],e:[['المقصور','آخره ألف لازمة: فتى، عصا، مستشفى.'],['المنقوص','آخره ياء لازمة مكسور ما قبلها: القاضي، المحامي. تحذف الياء نكرة غير مضافة في الرفع والجر.'],['الممدود','آخره همزة قبلها ألف زائدة: سماء، صحراء، بناء.']],sum:'المقصور ألف، والمنقوص ياء، والممدود همزة قبلها ألف.',q:[['مصطفى اسم:', ['منقوص','مقصور','ممدود','صحيح'],1],['صحراء اسم:', ['ممدود','مقصور','منقوص','مهموز'],0],['الاسم المنقوص في جاء المحامي:', ['جاء','المحكمة','المحامي','إلى'],2],['حذفت ياء رامٍ لأنه:', ['معرفة','نكرة غير مضاف','جمع','للتخفيف'],1]]},
{id:'biology',s:'العلوم الحياتية',t:'تركيب الخلية ووظائف مكوناتها',i:'🔬',d:'الخلية والعضيات ووظائفها.',intro:'الخلية وحدة البناء والوظيفة في الكائنات الحية.',o:['تحديد الغشاء والسيتوبلازم والنواة.','التعرف على العضيات.','ربط العضية بوظيفتها.'],e:[['الأجزاء الرئيسية','الغشاء البلازمي ينظم مرور المواد، السيتوبلازم وسط التفاعلات، والنواة مركز التحكم وتحوي DNA.'],['العضيات','الميتوكندريا للطاقة، الريبوسومات للبروتين، غولجي للتعديل والتغليف، والبلاستيدات للبناء الضوئي.']],sum:'النواة للتحكم، الميتوكندريا للطاقة، الريبوسومات للبروتين، وغولجي للتغليف.',q:[['العضي المسؤول عن إنتاج الطاقة:', ['النواة','غولجي','الميتوكندريا','الريبوسومات'],2],['مركز التحكم ويحتوي المادة الوراثية:', ['السيتوبلازم','النواة','الغشاء','الفجوات'],1],['الريبوسومات تقوم بـ:', ['هضم الفضلات','بناء البروتينات','إنتاج الطاقة','البناء الضوئي'],1],['العضي النباتي للبناء الضوئي:', ['الجدار','البلاستيدات الخضراء','الميتوكندريا','المركزات'],1]]},
{id:'earth',s:'علوم الأرض',t:'المياه السطحية',i:'🌍',d:'المياه السطحية والجريان السطحي والأحواض المائية.',intro:'المياه السطحية تشمل الأنهار والبحيرات والجريان السطحي.',o:['فهم الجريان السطحي.','معرفة العوامل المؤثرة فيه.','فهم الحوض المائي.'],e:[['الجريان السطحي','جزء من الهطل يجري على سطح الأرض ولا يتبخر أو يتسرب.'],['العوامل','الانحدار والهطل والصخور الكتيمة تزيد الجريان، بينما النبات والرمل يزيدان التسرب.']],sum:'الجريان يتأثر بالهطل والانحدار والتربة والصخور والغطاء النباتي.',q:[['المياه التي تجري على السطح:', ['مياه جوفية','جريان سطحي','تبخر','تكاثف'],1],['ما الذي يقلل الجريان؟',['غطاء نباتي كثيف','انحدار شديد','صخور كتيمة','غزارة المطر'],0],['المساحة التي تتجه مياهها لمجرى واحد:', ['مياه جوفية','حوض مائي','نبع','جليديات'],1],['العلاقة بين الانحدار والجريان:', ['عكسية','طردية','لا توجد','ثابتة'],1]]},
{id:'chemistry',s:'الكيمياء',t:'خصائص الحموض والقواعد',i:'🧪',d:'الحموض والقواعد والكواشف وpH.',intro:'نميز الحموض والقواعد باستخدام الكواشف ومقياس pH.',o:['تعداد الخصائص.','معرفة أثرها على تباع الشمس.','التعرف على H+ وOH-.'],e:[['الحموض','تنتج H+، تحوّل الأزرق إلى الأحمر، وpH أقل من 7.'],['القواعد','تنتج OH-، تحوّل الأحمر إلى الأزرق، وpH أكبر من 7.'],['pH','أقل من 7 حمضي، 7 متعادل، أكبر من 7 قاعدي.']],sum:'الحموض H+ وpH<7، والقواعد OH- وpH>7.',q:[['الأيون المرتبط بالخواص الحمضية:', ['O','OH-','H+','Cl-'],2],['الأحمر إلى الأزرق يعني:', ['حمض','قاعدة','ملح','ماء'],1],['pH=3 يعني:', ['حمض','قاعدة','متعادل','لا يمكن'],0],['الماء النقي pH:', ['0','14','7','5'],2]]},
{id:'physics',s:'الفيزياء',t:'أخطاء القياس',i:'⚖️',d:'الدقة والضبط والأخطاء العشوائية والمنتظمة.',intro:'لا يوجد قياس خالٍ تمامًا من الخطأ.',o:['التمييز بين العشوائي والمنتظم.','تحديد مصادر الخطأ.','التمييز بين الدقة والضبط.'],e:[['العشوائي','متذبذب وقد يكون بالزيادة أو النقصان، ويقل بالتكرار والمتوسط.'],['المنتظم','في اتجاه واحد غالبًا بسبب المعايرة أو الخطأ الصفري.'],['الدقة والضبط','الدقة قرب الحقيقة، والضبط تقارب القياسات.']],sum:'العشوائي متذبذب، والمنتظم ثابت الاتجاه. الدقة قرب الحقيقة والضبط تقارب النتائج.',q:[['الخطأ في اتجاه واحد يسمى:', ['العشوائي','المنتظم','الضبط','الدقة'],1],['من مصادر الخطأ المنتظم:', ['الخطأ الصفري','تيارات الهواء','اختلاف النظر','الاهتزاز'],0],['تقليل العشوائي يكون بـ:', ['تغيير الأداة','التكرار والمتوسط','المعايرة','قيم كبيرة'],1],['القرب من القيمة الحقيقية يسمى:', ['الضبط','الدقة','الخطأ المئوي','المتوسط'],1]]},
{id:'english',s:'اللغة الإنجليزية',t:'Vocabulary & Grammar (Module 1)',i:'🔠',d:'Past Simple وPast Continuous مع when وwhile.',intro:'Learn the difference between Past Simple and Past Continuous.',o:['Use vocabulary correctly.','Differentiate between the two tenses.','Use when and while.'],e:[['Past Simple','Completed actions in the past: Subject + V2.'],['Past Continuous','Actions in progress: was/were + V-ing.'],['When / While','While غالبًا مع المستمر، وWhen مع الحدث القصير.']],sum:'Past Simple للأحداث المنتهية، وPast Continuous للأحداث المستمرة.',q:[['I ___ to the radio when I heard the news.',['listened','was listening','am listening','listen'],1],['They ___ football yesterday at 5 PM.',['were playing','played','are playing','play'],0],['While she ___ a book, the lights went out.',['read','is reading','was reading','reads'],2],['What ___ you doing when the earthquake happened?',['are','did','was','were'],3]]}
];
let done=new Set(JSON.parse(localStorage.getItem('g9done')||'[]')),quiz=null,qi=0,score=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function show(id){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo(0,0)}
function progress(){let p=Math.round(done.size/D.length*100);$('#progressText').textContent=p+'%';$('#progressBar').style.width=p+'%'}
function subjects(){ $('#subjects').innerHTML=D.map(x=>`<div class="subject" onclick="openLesson('${x.id}')"><div class="icon">${x.i}</div><h3>${x.s}</h3><p>${x.t}</p><span class="tag">${done.has(x.id)?'✓ مكتمل':'ابدئي الدرس'}</span></div>`).join('') }
function lessons(){let f=$('#filter').value,list=f==='all'?D:D.filter(x=>x.id===f);$('#lessonGrid').innerHTML=list.map(x=>`<div class="lesson-card"><div class="icon">${x.i}</div><small>${x.s}</small><h3>${x.t}</h3><p>${x.d}</p><button class="primary" onclick="openLesson('${x.id}')">فتح الدرس</button> <button onclick="startQuiz('${x.id}')">اختبار</button></div>`).join('')}
function activityFor(x){
  if(x.id==='math') return `<p>اختاري التحويل الصحيح للدالة.</p><div class="activity"><button onclick="mathInfo(0)">g(x)=x²+5</button><button onclick="mathInfo(1)">g(x)=(x-3)²</button><button onclick="mathInfo(2)">g(x)=(x+2)²-4</button></div><p id="math" class="panel"></p>`;
  if(x.id==='arabic') return `<p>اختاري نوع الاسم الصحيح.</p><div class="activity"><button onclick="arabicInfo('مصطفى')">مصطفى</button><button onclick="arabicInfo('صحراء')">صحراء</button><button onclick="arabicInfo('القاضي')">القاضي</button><button onclick="arabicInfo('عصا')">عصا</button></div><p id="arabic" class="panel"></p>`;
  if(x.id==='biology') return `<p>اختاري العضية لمعرفة وظيفتها.</p><div class="activity">${['النواة','الميتوكندريا','الريبوسومات','أجسام غولجي'].map(a=>`<button onclick="this.parentElement.nextElementSibling.textContent='${a}: '+bioInfo('${a}')">${a}</button>`).join('')}</div><p id="bio" class="panel"></p>`;
  if(x.id==='earth') return `<p>اختاري العامل لمعرفة تأثيره في الجريان السطحي.</p><select class="select" onchange="earthInfo(this.value)"><option value="">اختاري العامل</option><option value="s">انحدار شديد</option><option value="t">أشجار كثيفة</option><option value="r">صخور كتيمة</option><option value="a">تربة رملية</option></select><p id="earth" class="panel"></p>`;
  if(x.id==='chemistry') return `<p>حرّكي المؤشر لمعرفة طبيعة المحلول.</p><input id="ph" type="range" min="0" max="14" value="7" style="width:90%"><h3>pH = <span id="phv">7</span></h3><div id="phr" class="panel">متعادل</div>`;
  if(x.id==='physics') return `<p>هل الخطأ التالي عشوائي أم منتظم؟</p><p>عدم تصفير الميزان قبل القياس.</p><div class="activity"><button onclick="phys('منتظم')">منتظم</button><button onclick="phys('عشوائي')">عشوائي</button></div><p id="phys" class="panel"></p>`;
  if(x.id==='english') return `<p>اختاري الإجابة الصحيحة لإكمال الجملة.</p><div class="panel"><b>I ___ to the radio when I heard the news.</b><div class="activity"><button onclick="englishInfo(this, false)">listened</button><button onclick="englishInfo(this, true)">was listening</button></div></div><div class="panel"><b>While she ___ a book, the lights went out.</b><div class="activity"><button onclick="englishInfo(this, false)">read</button><button onclick="englishInfo(this, true)">was reading</button></div></div><p id="english" class="panel"></p>`;
  return '';
}
function openLesson(id){let x=D.find(a=>a.id===id);$('#detail').innerHTML=`<div class="detail-head"><div style="font-size:3rem">${x.i}</div><small style="color:#eee">${x.s}</small><h2>${x.t}</h2><p>${x.intro}</p></div><div class="panel"><h3>🎯 أهداف التعلم</h3><ul>${x.o.map(a=>`<li>${a}</li>`).join('')}</ul></div>${x.e.map(a=>`<div class="panel"><h3>${a[0]}</h3><p>${a[1]}</p></div>`).join('')}<div class="interactive"><h3>✨ نشاط سريع</h3>${activityFor(x)}</div><div class="panel"><h3>📌 الخلاصة</h3><p>${x.sum}</p></div><div style="text-align:center"><button class="primary" onclick="complete('${x.id}')">${done.has(x.id)?'✓ مكتمل':'وضع علامة كمكتمل'}</button> <button onclick="startQuiz('${x.id}')">ابدئي الاختبار</button></div>`;show('lesson')}
function complete(id){done.add(id);localStorage.setItem('g9done',JSON.stringify([...done]));progress();subjects();lessons();openLesson(id)}
function bioInfo(a){return {النواة:'مركز التحكم وتحوي DNA',الميتوكندريا:'إنتاج الطاقة',الريبوسومات:'بناء البروتينات','أجسام غولجي':'تغليف وإفراز المواد'}[a]}
function earthInfo(v){$('#earth').textContent={s:'يزداد الجريان السطحي.',t:'يقل الجريان ويزداد التسرب.',r:'يزداد الجريان لعدم النفاذ.',a:'يقل الجريان ويزداد التسرب.'}[v]||''}
function phys(v){$('#phys').textContent=v==='منتظم'?'إجابة صحيحة ✅':'إجابة غير صحيحة ❌'}
function mathInfo(n){$('#math').textContent=[
  'إضافة 5 تنقل القطع المكافئ إلى الأعلى 5 وحدات.',
  'طرح 3 من x ينقل القطع المكافئ إلى اليمين 3 وحدات.',
  'الإشارة الموجبة داخل القوس تنقله إلى اليسار 2، و-4 تنقله إلى الأسفل 4.'
][n]}
function arabicInfo(a){$('#arabic').textContent={مصطفى:'مقصور: ينتهي بألف لازمة.',صحراء:'ممدود: ينتهي بهمزة قبلها ألف زائدة.',القاضي:'منقوص: ينتهي بياء لازمة مكسور ما قبلها.',عصا:'مقصور: ينتهي بألف لازمة.'}[a]||''}
function englishInfo(btn,correct){btn.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true);$('#english').textContent=correct?'إجابة صحيحة ✅':'إجابة غير صحيحة ❌'}
function startQuiz(id){quiz=D.find(x=>x.id===id);qi=0;score=0;show('quiz');pick();question()}
function pick(){$('#quizPicker').innerHTML=D.map(x=>`<button onclick="startQuiz('${x.id}')">${x.i} ${x.s}</button>`).join('')}
function question(){if(!quiz)return;if(qi>=quiz.q.length){$('#quizArea').innerHTML=`<div class="quizbox" style="text-align:center"><h2>🎉 انتهى الاختبار</h2><p>نتيجتك في ${quiz.s}: <b>${score}/${quiz.q.length}</b></p><button class="primary" onclick="startQuiz('${quiz.id}')">إعادة الاختبار</button></div>`;return}let q=quiz.q[qi];$('#quizArea').innerHTML=`<div class="quizbox"><small>السؤال ${qi+1} من ${quiz.q.length}</small><h3>${q[0]}</h3>${q[1].map((o,i)=>`<button class="option" onclick="answer(${i},${q[2]})">${o}</button>`).join('')}<p id="msg"></p><button id="next" class="primary" disabled onclick="qi++;question()">التالي</button></div>`}
function answer(i,c){let bs=$$('.option');bs.forEach((b,n)=>{b.disabled=true;if(n===c)b.classList.add('correct');if(n===i&&i!==c)b.classList.add('wrong')});if(i===c){score++;$('#msg').textContent='إجابة صحيحة ✅'}else $('#msg').textContent='إجابة غير صحيحة ❌';$('#next').disabled=false}
$$('nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#allBtn').onclick=()=>show('lessons');$('#filter').onchange=lessons;D.forEach(x=>$('#filter').insertAdjacentHTML('beforeend',`<option value="${x.id}">${x.s}</option>`));subjects();lessons();pick();progress();
document.addEventListener('input',e=>{if(e.target.id==='ph'){let v=+e.target.value;$('#phv').textContent=v;$('#phr').textContent=v<7?'حمضي 🔴':v>7?'قاعدي 🔵':'متعادل ⚪'}});
